FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache git
RUN go build -o /out/processor-server ./cmd/processor-server

FROM alpine:3.18
COPY --from=build /out/processor-server /usr/local/bin/processor-server
EXPOSE 9090
ENTRYPOINT ["/usr/local/bin/processor-server"]
