
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "streamflow/processor"


)

var tests = []testing.InternalTest{

	{"TestWindowAggregateOperator", _test.TestWindowAggregateOperator},

	{"TestJoinOperator", _test.TestJoinOperator},

	{"TestProcessorPipeline", _test.TestProcessorPipeline},

	{"TestProcessorEchoStream", _test.TestProcessorEchoStream},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "streamflow"
	testdeps.ImportPath = "streamflow/processor"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

