
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "streamflow/broker/internal/raft"


)

var tests = []testing.InternalTest{

	{"TestThreeNodeInProcClusterReplication", _test.TestThreeNodeInProcClusterReplication},

	{"TestRotateCAAndIssueCert", _test.TestRotateCAAndIssueCert},

	{"TestSingleNodeRestart", _test.TestSingleNodeRestart},

	{"TestClusterRollingRestart", _test.TestClusterRollingRestart},

	{"TestWALCompactionKeepsLaterEntries", _test.TestWALCompactionKeepsLaterEntries},

	{"TestWALMinIOIntegration", _test.TestWALMinIOIntegration},

	{"TestWALSaveAndRestoreViaOffload", _test.TestWALSaveAndRestoreViaOffload},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "streamflow"
	testdeps.ImportPath = "streamflow/broker/internal/raft"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

