
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "streamflow/streamql"


)

var tests = []testing.InternalTest{

	{"TestExecuteSimplePlan", _test.TestExecuteSimplePlan},

	{"TestExecuteGroupByCount", _test.TestExecuteGroupByCount},

	{"TestExecuteSumAvgGroupBy", _test.TestExecuteSumAvgGroupBy},

	{"TestExecuteWindowSum", _test.TestExecuteWindowSum},

	{"TestParseSimpleSelect", _test.TestParseSimpleSelect},

	{"TestPlanify", _test.TestPlanify},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "streamflow"
	testdeps.ImportPath = "streamflow/streamql"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

